// THIS FILE IS AUTOGENERATED BY scripts/generate_tasia_giphy_key.py
// Do not edit manually. Do not commit this generated file.

#ifndef LL_TASIA_GIPHY_KEY_GENERATED_H
#define LL_TASIA_GIPHY_KEY_GENERATED_H

#include <string>

namespace LLTasiaGiphyKeyGenerated
{
std::string getAPIKey();
bool hasAPIKey();
}

#endif // LL_TASIA_GIPHY_KEY_GENERATED_H
