// THIS FILE IS AUTOGENERATED BY scripts/generate_tasia_giphy_key.py
// Do not edit manually. Do not commit this generated file.

#include "llviewerprecompiledheaders.h"

#include "lltasia_giphy_key.generated.h"

#include <cstddef>

namespace
{
static const U32 kSeed = 0x97b634e7u;
static const U8 kSalt[] = {
    0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a, 0x5a,
    0x5a, 0x5a, 0x5a, 0x5a
};
static const U8 kData[] = {
0
};
static const std::size_t kLength = 0u;

U8 maskByte(std::size_t index)
{
    U32 state = kSeed + static_cast<U32>((index + 1u) * 0x9E3779B9u);
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return static_cast<U8>((state & 0xffu) ^ kSalt[index % sizeof(kSalt)] ^ ((index * 31u) & 0xffu));
}
}

namespace LLTasiaGiphyKeyGenerated
{
std::string getAPIKey()
{
    std::string key;
    key.reserve(kLength);
    for (std::size_t index = 0; index < kLength; ++index)
    {
        key.push_back(static_cast<char>(kData[index] ^ maskByte(index)));
    }
    return key;
}

bool hasAPIKey()
{
    return kLength > 0u;
}
}
